import { OnInit, EventEmitter, ElementRef } from '@angular/core';
import { AtGlobalMonitorService, Position } from "../at-global-monitor.service";
export declare class ModalComponent implements OnInit {
    private global_service;
    constructor(global_service: AtGlobalMonitorService);
    ngOnInit(): void;
    state: string;
    position: Position;
    icon_status: {
        'info': string;
        'error': string;
        'warning': string;
        'success': string;
        'loading': string;
    };
    private _closeable;
    private _atType;
    private _status;
    private _show;
    private _message;
    width: number;
    top: number;
    maskClose: boolean;
    onCancel: EventEmitter<boolean>;
    onOk: EventEmitter<boolean>;
    modal_content: ElementRef;
    closeable: boolean;
    message: string;
    title: string;
    atType: "normal" | "confirm";
    status: "error" | "success" | "warning" | "info";
    show: boolean;
    cancel(): void;
    setShow(): void;
    positionStyle: {};
    setStyle(): {};
    ok(): void;
    cancelFromMask(e: any): void;
    customTitle: ElementRef;
    headerContains(): boolean;
}
